# Generated by Django 4.2 on 2023-05-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("sobrenome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha", models.CharField(max_length=8)),
            ],
        ),
    ]
